=== minkyong00/web_study/ajax/persons.dtd
<!ELEMENT persons (person+)>
<!ELEMENT person (name, age, address)>
<!ATTLIST person
    pid ID #REQUIRED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT address (#PCDATA)>

=== minkyong00/web_study/ajax/persons.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="persons.css"?>
<!DOCTYPE persons SYSTEM "persons.dtd">
<persons>
    <person pid="pid1">
        <name>홍길동</name>
        <age>30</age>
        <address>지구 어딘가</address>
    </person>
    <person pid="pid2">
        <name>강감찬</name>
        <age>20</age>
        <address>우주 어딘가</address>
    </person>
</persons>
